# Generated by Django 3.0.6 on 2020-05-26 09:19

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            related_name='restaurants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('code', models.UUIDField(default=uuid.uuid4,
                                          editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('max_purchase_count', models.PositiveIntegerField(
                    default=0, help_text='Number of coupons/tickets can be purchased.', validators=[django.core.validators.MinValueValidator(0)])),
                ('purchased_count', models.PositiveIntegerField(
                    default=0, help_text='Number of coupons/tickets already purchased.', validators=[django.core.validators.MinValueValidator(0)])),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='tickets', to='restaurants.Restaurants')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
