# Generated by Django 3.0.6 on 2020-05-27 15:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('count', models.PositiveIntegerField(default=0, help_text='Number of tickets to be purchased.', validators=[django.core.validators.MinValueValidator(0)])),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='restaurants.Tickets')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
